// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_taylorswift_ = (function() {
  function block_taylorswift_() {
    this.filter_items = bind(this.filter_items, this);
    this.run = bind(this.run, this);
    var css;
    this.taylor_swift = {
      name: "taylor swift",
      instagram_id: 11830955,
      vid_id: "QcIy9NiNbmo"
    };
    css = "#instafeed {\n	display: none;\n}\n\n.taylor-image {\n	height:130%;\n	position: relative;\n	left: -65px;\n	top:0px;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable celebrity celeb Who\" name=\"taylorswift\">\n	<img class=\"taylor-image\" src=\"img/taylorswift.jpg\">\n	<div id=\"instafeed\"></div>\n</div>").appendTo(".drag-zone");
  }

  block_taylorswift_.prototype.run = function() {
    return this.taylor_swift;
  };

  block_taylorswift_.prototype.filter_items = function() {
    var block, i, name, results, temp_list;
    temp_list = $(".draggable.What");
    i = 0;
    results = [];
    while (i < temp_list.length) {
      name = $(temp_list[i]).attr("name");
      block = window["block_" + name];
      if (name === "instagram_competition") {
        block.filter_items();
      }
      results.push(i++);
    }
    return results;
  };

  return block_taylorswift_;

})();
