// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_instagram_competition_ = (function() {
  function block_instagram_competition_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable celeb What\" name=\"instagram_competition\">\n	<img style='width:100%;height:auto;position:absolute;top:16%;left:0%;' src='http://d13zeczpqm2715.cloudfront.net/wp-content/uploads/2015/06/instagram-logo-vector-image.png'>\n</div>").appendTo(".drag-zone");
  }

  block_instagram_competition_.prototype.run = function() {
    return "instagram_competition";
  };

  return block_instagram_competition_;

})();
