// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_instagram_competition_ = (function() {
  function block_instagram_competition_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable celeb\" name=\"instagram_competition\">\n	Instagram Competition\n</div>").appendTo(".drag-zone");
  }

  block_instagram_competition_.prototype.run = function() {
    return "instagram_competition";
  };

  return block_instagram_competition_;

})();
