// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_beyonce_ = (function() {
  function block_beyonce_() {
    this.filter_items = bind(this.filter_items, this);
    this.run = bind(this.run, this);
    var css;
    this.beyonce = {
      name: "beyonce",
      instagram_id: 247944034,
      vid_id: "k4YRWT_Aldo"
    };
    css = "#instafeed {\n	display: none;\n}\n\n.beyonce-image {\n	height:100%;\n	position: relative;\n	left: -40px;\n	bottom:0;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable celebrity Who\" name=\"beyonce\">\n	<img class='beyonce-image' src=\"img/beyonce.jpg\">\n<div id=\"instafeed\"></div>\n</div>").appendTo(".drag-zone");
  }

  block_beyonce_.prototype.run = function() {
    return this.beyonce;
  };

  block_beyonce_.prototype.filter_items = function() {
    var block, i, name, results, temp_list;
    temp_list = $(".draggable.What");
    i = 0;
    results = [];
    while (i < temp_list.length) {
      name = $(temp_list[i]).attr("name");
      block = window["block_" + name];
      if (name === "instagram_competition") {
        block.filter_items();
      }
      results.push(i++);
    }
    return results;
  };

  return block_beyonce_;

})();
