// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.bubble_section_ = (function() {

  /*
  	Parameters:
  		left
  		top
  		diameter
  		bubble_type
   */
  function bubble_section_(left, top, diameter, bubble_type) {
    var css;
    this.left = left;
    this.top = top;
    this.diameter = diameter;
    this.revert = bind(this.revert, this);
    this.expand_section = bind(this.expand_section, this);
    if (window.bubble_counter == null) {
      window.bubble_counter = -1;
    }
    this.counter = ++window.bubble_counter;
    css = ".bubble-section-" + this.counter + " {\n	position: absolute;\n	top: " + this.top + "px;\n	left: " + this.left + "px;\n	width: " + this.diameter + "px;\n	height: " + this.diameter + "px;\n	border: 1px black solid;\n	background: rgba(255, 255, 255,0.8);\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class='steps bubble-sections bubble-section-" + this.counter + "' role='bubble_section' type='" + bubble_type + "'>\n	<div id='bubble-text-" + this.counter + "'>" + bubble_type + "</div>\n</div>").appendTo(".drop-zone");
    this.drag_zone = new control_drag_zone_(12, 20, 350, 'source', this);
    this.drag_zone.hide();
    $(".bubble-section-" + this.counter).on('tap click', (function(_this) {
      return function() {

        /*
        			bubble section will expand and become a drop zone
        			don't worry about animations yet
         */
        return _this.expand_section();
      };
    })(this));
  }

  bubble_section_.prototype.expand_section = function() {
    $(".bubble-sections:not(.bubble-section-" + this.counter + ")").velocity("fadeOut", {
      duration: 1000
    });
    $(".bubble-section-" + this.counter).velocity({
      width: 350,
      height: 350,
      top: 20,
      left: 12
    }, {
      duration: 1000,
      complete: (function(_this) {
        return function() {
          $(".bubble-section-" + _this.counter).css({
            visibility: 'hidden'
          });
          return _this.drag_zone.show();
        };
      })(this)
    });
    console.log($("#bubble-text-" + this.counter)[0]);
    return $("#bubble-text-" + this.counter).velocity("fadeOut", {
      duration: 500,
      complete: (function(_this) {
        return function() {
          $("#bubble-text-" + _this.counter).text("Drag Here");
          return $("#bubble-text-" + _this.counter).velocity("fadeIn", {
            duration: 500
          });
        };
      })(this)
    });
  };

  bubble_section_.prototype.revert = function() {
    this.drag_zone.hide();
    console.log("Going back");
    $(".bubble-section-" + this.counter).html($(".dragged-block-" + (this.drag_zone.get_id())).html());
    console.log($(".dragged-block-" + (this.drag_zone.get_id())).html());
    $(".dragged-block-" + (this.drag_zone.get_id())).css({
      display: 'none'
    });
    $(".bubble-section-" + this.counter).css({
      visibility: 'visible'
    });
    $(".bubble-section-" + this.counter).velocity({
      width: this.diameter,
      height: this.diameter,
      top: this.top,
      left: this.left
    }, {
      duration: 1000
    });
    return $(".bubble-sections:not(.bubble-section-" + this.counter + ")").velocity("fadeIn", {
      duration: 1000
    });
  };

  return bubble_section_;

})();
