// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_ding_ = (function() {
  function block_ding_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable action Why\" name=\"ding\">\n	<img style='width:80%;height:80%;position:absolute;top:9%;left:9%;' src='http://iconshow.me/media/images/ui/iOS7-optimized-icon/png/256/43.bell.png'>\n</div>").appendTo(".drag-zone");
    this.audio = null;
  }

  block_ding_.prototype.run = function(obj, cb) {
    if (this.audio === null) {
      this.audio = new Audio("./sound/Ding.mp3");
    }
    this.audio.pause();
    return this.audio.play();
  };

  return block_ding_;

})();
