// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_pizza_ = (function() {
  function block_pizza_() {
    this.run = bind(this.run, this);
    var css;
    css = ".pizza {\n	background-image: url(img/pizza.jpeg);\n	background-size: cover;\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable action Why pizza general_action\" name=\"pizza\">\n</div>").appendTo(".drag-zone");
  }

  block_pizza_.prototype.run = function() {
    console.log("Ordered a pizza");
    return alert("Ordered a pizza!");
  };

  return block_pizza_;

})();
