// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_display_image_ = (function() {
  function block_display_image_() {
    this.display_individual_image = bind(this.display_individual_image, this);
    this.run = bind(this.run, this);
    var css;
    css = ".display-image-text {\n	position: absolute;\n	top: 6px;\n	left: 4px;\n	color: blue;\n	font-weight: bold;\n}\n\n.display-image-icon {\n	position: absolute;\n	top: 25px;\n	left: 20px;\n	color: grey;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div style='overflow: visible' class=\"drag-wrap draggable action Why\" name=\"display_image\">\n	<i class=\"fa fa-picture-o fa-5x display-image-icon\"></i>\n	<p class='display-image-text'>DISPLAY IMAGE</p>\n</div>").appendTo(".drag-zone");
  }

  block_display_image_.prototype.run = function(list) {
    return async.forEachOfSeries(list, (function(_this) {
      return function(element, i, cb) {
        return _this.display_individual_image(element, cb);
      };
    })(this), function(err) {
      return alert("all done");
    });
  };

  block_display_image_.prototype.display_individual_image = function(obj, cb) {
    var url;
    url = obj.images.standard_resolution.url;
    $('<div id="white-background"></div><div id="image-div"></div><img class="new_image" src=' + url + ' />').appendTo("body");
    $('#white-background').css({
      backgroundColor: 'white',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
      position: 'fixed',
      margin: 0,
      top: 0,
      bottom: 0,
      right: 0,
      left: 0,
      width: '100%',
      height: '100%',
      zIndex: 10000000
    });
    $('#image-div').css({
      backgroundImage: "url(" + url + ")",
      backgroundSize: 'cover',
      backgroundPosition: 'center',
      position: 'fixed',
      margin: 0,
      top: '-50%',
      bottom: 0,
      right: 0,
      left: '-50%',
      width: '200%',
      height: '200%',
      zIndex: 10000001,
      opacity: 0.35,
      transform: 'rotate(15deg)'
    });
    $('.new_image').css({
      maxWidth: '120%',
      maxHeight: '100%',
      bottom: 0,
      left: 0,
      margin: 'auto',
      overflow: 'auto',
      position: 'fixed',
      right: 0,
      top: 0,
      zIndex: 10000002
    });
    return setTimeout(cb, 2000);
  };

  return block_display_image_;

})();
