// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_youtube_ = (function() {
  function block_youtube_() {
    this.create_player = bind(this.create_player, this);
    this.youtube_app = bind(this.youtube_app, this);
    this.run = bind(this.run, this);
    var css;
    css = "#youtube_pic{\n	position: absolute;\n	left: 20px;\n	top: 25px;\n	width: 100px;\n	height: 100px;\n}\n\n#youtube_player {\n	position: absolute;\n	top: 0px;\n	left: -144px;\n}\n";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable Why\" name=\"youtube\">\n	<div id=\"youtube_player\"></div>\n	<img id=\"youtube_pic\" src=\"img/youtube-logo.png\">\n</div>").appendTo(".drag-zone");
  }

  block_youtube_.prototype.run = function(people) {
    console.log("Got in youtube");
    console.log(people);
    return this.youtube_app(people);
  };

  block_youtube_.prototype.youtube_app = function(people) {
    return this.create_player(people);
  };

  block_youtube_.prototype.create_player = function(people) {
    var firstScriptTag, tag;
    tag = document.createElement('script');
    tag.src = "https://www.youtube.com/player_api";
    firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
    return window.onYouTubeIframeAPIReady = (function(_this) {
      return function() {
        var player;
        return player = new YT.Player('youtube_player', {
          height: '352',
          videoId: people[0].vid_id,
          events: {
            onReady: function(e) {
              console.log("youtube onReady");
              return e.target.playVideo();
            },
            onStateChange: function(e) {
              return console.log("youtube onStateChange");
            }
          }
        });
      };
    })(this);
  };

  return block_youtube_;

})();
