// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_gmail_ = (function() {
  function block_gmail_() {
    this.filter_items = bind(this.filter_items, this);
    this.run = bind(this.run, this);
    var css;
    css = "[name=gmail] {\n	background-image: url(img/Gmail-icon.png);\n	background-size: cover;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable action Why\" name=\"gmail\">\n</div>").appendTo(".drag-zone");
  }

  block_gmail_.prototype.run = function(images) {
    var length, title, url;
    images = images[0];
    if (images.images !== void 0) {
      url = images.images.standard_resolution.url;
      title = images.caption.text;
    } else if (images.entities.media !== void 0) {
      url = images.entities.media[0].media_url;
      title = images.text;
    } else {
      url = images.user.profile_image_url;
      length = images.user.profile_image_url.length;
      if (url[url.length - 2] === "e") {
        url = url.slice(0, url.length - 12) + ".jpeg";
      } else {
        url = url.slice(0, url.length - 11) + ".jpg";
      }
      title = images.text;
    }
    return $.ajax({
      url: "/gmail?content=<img src = " + url + ">&title=" + title,
      dataType: 'json',
      type: "GET",
      error: function(jqXHR, textStatus, errorThrown) {},
      success: function(data, textStatus, jqXHR) {}
    });
  };

  block_gmail_.prototype.filter_items = function() {
    var block, i, name, results, temp_list;
    temp_list = $(".draggable.What");
    i = 0;
    results = [];
    while (i < temp_list.length) {
      name = $(temp_list[i]).attr("name");
      block = window["block_" + name];
      if (name === "instagram_competition") {
        block.filter_items();
      }
      results.push(i++);
    }
    return results;
  };

  return block_gmail_;

})();
