// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_gates_ = (function() {
  function block_gates_() {
    this.run = bind(this.run, this);
    var css, northEastLat, northEastLng, northWestLat, northWestLng, southEastLat, southEastLng, southWestLat, southWestLng;
    southWestLat = 37.43002367;
    southWestLng = -122.17403859;
    northWestLat = 37.43057319;
    northWestLng = -122.17377573;
    northEastLat = 37.43031334;
    northEastLng = -122.1729067;
    southEastLat = 37.4297766;
    southEastLng = -122.17311054;
    css = ".gates {\n	background-image: url(http://gaspull.geeksaresexytech.netdna-cdn.com/wp-content/uploads/2009/09/cs2.jpg);\n	background-size: cover;\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"gates drag-wrap draggable stanford_place filter Where\" name=\"gates\">\n</div>").appendTo(".drag-zone");
    this.rectangle = [new google.maps.LatLng(southWestLat, southWestLng), new google.maps.LatLng(northWestLat, northWestLng), new google.maps.LatLng(northEastLat, northEastLng), new google.maps.LatLng(southEastLat, southEastLng)];
  }

  block_gates_.prototype.run = function() {
    return this.rectangle;
  };

  return block_gates_;

})();
