// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_yogurtland_ = (function() {
  function block_yogurtland_() {
    this.run = bind(this.run, this);
    var css, northEastLat, northEastLng, northWestLat, northWestLng, southEastLat, southEastLng, southWestLat, southWestLng;
    southWestLat = 37.428289997495774;
    southWestLng = -122.167537441803;
    northWestLat = 37.42743800008019;
    northWestLng = -122.16646455819705;
    northEastLat = 37.428289997495774;
    northEastLng = -122.16646455819705;
    southEastLat = 37.428289997495774;
    southEastLng = -122.167537441803;
    css = "#yogurtland {\n	background-image: url(http://api.ning.com/files/fOx4UMMDlAl-5LS2ubi2b5YI9wdZrJt0xWoMPKpNtfrAw1KnxmFk*Gzb0v9EbtmbTn8499zdCaXXtX0JMSrIp-tbPIE83gkC/yogurtland.jpg);\n	background-size: cover;\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div id=\"yogurtland\" class=\"drag-wrap draggable filter Where\" name=\"yogurtland\">\n</div>").appendTo(".drag-zone");
    this.rectangle = [new google.maps.LatLng(southWestLat, southWestLng), new google.maps.LatLng(northWestLat, northWestLng), new google.maps.LatLng(northEastLat, northEastLng), new google.maps.LatLng(southEastLat, southEastLng)];
  }

  block_yogurtland_.prototype.run = function() {
    return this.rectangle;
  };

  return block_yogurtland_;

})();
