// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_map_ = (function() {
  function block_map_() {
    this.run = bind(this.run, this);
    this.get_rectangle_coords = bind(this.get_rectangle_coords, this);
    var css;
    css = "#google_map{\n	width: 100px;\n	height: 100px;\n	left: 7px;\n	top: 7px;\n	line-height: 0px;\n	border-radius: 50%\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"map\">\n	<div id='google_map'></div>\n</div>").appendTo(".drag-zone");
    $("#google_map").bind('touchstart mousedown', function() {
      return $("#google_map").parent().removeClass("draggable").addClass("not_draggable");
    });
    $("body").bind('touchend mouseup', function() {
      return $("#google_map").parent().removeClass("not_draggable").addClass("draggable");
    });
    google.maps.event.addDomListener(window, 'load', (function(_this) {
      return function() {
        var map_prop, my_lat, my_lng;
        my_lat = 37.427864;
        my_lng = -122.167001;
        map_prop = {
          center: new google.maps.LatLng(my_lat, my_lng),
          zoom: 17,
          mapTypeId: google.maps.MapTypeId.ROADMAP,
          disableDefaultUI: true,
          minZoom: 17,
          maxZoom: 17
        };
        _this.map = new google.maps.Map(document.getElementById("google_map"), map_prop);
        return _this.run();
      };
    })(this));
  }

  block_map_.prototype.get_rectangle_coords = function(bounds) {
    var northEast, northEastLat, northEastLng, northWestLat, northWestLng, southEastLat, southEastLng, southWest, southWestLat, southWestLng;
    northEast = bounds.getNorthEast();
    southWest = bounds.getSouthWest();
    southWestLat = southWest.lat();
    southWestLng = southWest.lng();
    northEastLat = northEast.lat();
    northEastLng = northEast.lng();
    southEastLat = northEast.lat();
    southEastLng = southWest.lng();
    northWestLng = northEast.lng();
    northWestLat = southWest.lat();
    console.log(northEastLat + ", " + northEastLng + "\n" + northWestLat + ", " + northWestLng + "\n" + southWestLat + ", " + southWestLng + "\n" + southEastLat + ", " + southEastLng);
    return [new google.maps.LatLng(southWestLat, southWestLng), new google.maps.LatLng(northWestLat, northWestLng), new google.maps.LatLng(northEastLat, northEastLng), new google.maps.LatLng(southEastLat, southEastLng)];
  };

  block_map_.prototype.run = function() {
    return navigator.geolocation.getCurrentPosition((function(_this) {
      return function(position) {
        var bounds, my_lat_lng, polygon_area, rectangle;
        _this.my_lat = 37.427864;
        _this.my_lng = -122.167001;
        my_lat_lng = new google.maps.LatLng(_this.my_lat, _this.my_lng);
        bounds = _this.map.getBounds();
        rectangle = _this.get_rectangle_coords(bounds);
        polygon_area = new google.maps.Polygon({
          paths: rectangle,
          strokeColor: '#FF0000',
          strokeOpacity: 0.8,
          strokeWeight: 3,
          fillColor: '#FF0000',
          fillOpacity: 0.35
        });
        polygon_area.setMap(_this.map);
        if (google.maps.geometry.poly.containsLocation(my_lat_lng, polygon_area)) {
          return true;
        } else {
          return false;
        }
      };
    })(this));
  };

  return block_map_;

})();
