// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_garden_ = (function() {
  function block_garden_() {
    this.run = bind(this.run, this);
    var css, northEastLat, northEastLng, northWestLat, northWestLng, southEastLat, southEastLng, southWestLat, southWestLng;
    southWestLat = 37.42800553;
    southWestLng = -122.16996532;
    northWestLat = 37.42796879;
    northWestLng = -122.16997202;
    northEastLat = 37.42797731;
    northEastLng = -122.16988888;
    southEastLat = 37.42802098;
    southEastLng = -122.16988552;
    css = ".garden {\n	background-image: url(\"img/sculpturegarden.jpg\");\n	background-size: cover;\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"garden drag-wrap draggable stanford_place filter Where\" name=\"garden\">\n</div>").appendTo(".drag-zone");
    this.rectangle = [new google.maps.LatLng(southWestLat, southWestLng), new google.maps.LatLng(northWestLat, northWestLng), new google.maps.LatLng(northEastLat, northEastLng), new google.maps.LatLng(southEastLat, southEastLng)];
  }

  block_garden_.prototype.run = function() {
    return this.rectangle;
  };

  return block_garden_;

})();
