// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_my_location_ = (function() {
  function block_my_location_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable source\" name=\"my_location\">\n	MY LOCATION\n</div>").appendTo(".drag-zone");
  }

  block_my_location_.prototype.run = function(cb) {
    return navigator.geolocation.getCurrentPosition((function(_this) {
      return function(position) {
        var my_lat, my_lat_lng, my_lng;
        my_lat = position.coords.latitude;
        my_lng = position.coords.longitude;
        my_lat_lng = new google.maps.LatLng(my_lat, my_lng);
        return cb(my_lat_lng);
      };
    })(this));
  };

  return block_my_location_;

})();
