// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.control_drop_area_ = (function() {
  function control_drop_area_() {
    this.show_winner = bind(this.show_winner, this);
    this.begin_competition = bind(this.begin_competition, this);
    this.run = bind(this.run, this);
    this.add_center_button = bind(this.add_center_button, this);
    this.add_bubble_sections = bind(this.add_bubble_sections, this);
    this.manual_drop = bind(this.manual_drop, this);
    this.get_randoms = bind(this.get_randoms, this);
    var css;
    css = ".drop_area {\n	position: relative;\n}\n.random_button {\n	position: absolute;\n	color: black;\n	top: 400px;\n	left: 340px;\n	width: 50px;\n	height: 50px;\n	visiblity: visible;\n}\n.random_area{\n	position: absolute;\n	top: 395px;\n	left: 333px;\n	width: 30px;\n	height: 30px;\n	border: 1px black solid;\n	background: rgba(255, 255, 255, 0.8);\n	border-radius: 50%;\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class='random_area'></div>\n<i class=\"random_button fa fa-random\"></i>\n\n<div id='current-step' class='text'></div>\n<div class='drop_area' role='drop_area'></div>").appendTo($("body"));
    this.add_bubble_sections();
    this.add_center_button();
    interact(".random_button").on('tap', (function(_this) {
      return function(event) {
        return _this.get_randoms();
      };
    })(this));
  }

  control_drop_area_.prototype.get_randoms = function() {
    var all_null, final_random, final_what, final_when, final_where, final_who, final_why, selected_list, selected_what, selected_when, selected_where, selected_who, selected_why, what_list, when_list, where_list, who_list, why_list;
    selected_list = [];
    who_list = $(".draggable.Who");
    if (who_list.length !== 0) {
      selected_who = Math.random() * who_list.length;
      selected_who = Math.floor(selected_who);
      final_who = who_list[selected_who];
      selected_list.push(final_who);
    } else {
      selected_list.push(null);
    }
    what_list = $(".draggable.What");
    if (what_list.length !== 0) {
      selected_what = Math.random() * what_list.length;
      selected_what = Math.floor(selected_what);
      final_what = what_list[selected_what];
      selected_list.push(final_what);
    } else {
      selected_list.push(null);
    }
    when_list = $(".draggable.When");
    if (when_list.length !== 0) {
      selected_when = Math.random() * when_list.length;
      selected_when = Math.floor(selected_when);
      final_when = when_list[selected_when];
      selected_list.push(final_when);
    } else {
      selected_list.push(null);
    }
    where_list = $(".draggable.Where");
    if (where_list.length !== 0) {
      selected_where = Math.random() * where_list.length;
      selected_where = Math.floor(selected_where);
      final_where = where_list[selected_where];
      selected_list.push(final_where);
    } else {
      selected_list.push(null);
    }
    why_list = $(".draggable.Why");
    if (why_list.length !== 0) {
      selected_why = Math.random() * why_list.length;
      selected_why = Math.floor(selected_why);
      final_why = why_list[selected_why];
      selected_list.push(final_why);
    } else {
      selected_list.push(null);
    }
    all_null = selected_list[0] === null && selected_list[1] === null && selected_list[2] === null && selected_list[3] === null && selected_list[4] === null;
    if (all_null !== true) {
      final_random = Math.random() * selected_list.length;
      final_random = Math.floor(final_random);
      while (selected_list[final_random] === null) {
        final_random = Math.random() * selected_list.length;
        final_random = Math.floor(final_random);
      }
      return this.manual_drop(selected_list[final_random], final_random);
    }
  };

  control_drop_area_.prototype.manual_drop = function(to_drop, type_of_block) {
    var $clone, block_name, block_offset, items, real_diameter, relative_left, relative_top, size, target, temp, x, y, zone_offset;
    target = $(".droppable-" + type_of_block);
    target.css({
      position: 'absolute'
    });
    block_name = $(to_drop).attr("name");
    this.block = window["block_" + block_name];
    if (type_of_block === 0) {
      this.who.set_block(this.block);
    } else if (type_of_block === 1) {
      this.what.set_block(this.block);
    } else if (type_of_block === 2) {
      this.when.set_block(this.block);
    } else if (type_of_block === 3) {
      this.where.set_block(this.block);
    } else if (type_of_block === 4) {
      this.why.set_block(this.block);
    }
    if (this.block.filter_items) {
      this.block.filter_items();
    }
    target.removeClass('can--catch');
    block_offset = $(to_drop).offset();
    zone_offset = target.offset();
    if ($(to_drop).hasClass('drag-wrap')) {
      real_diameter = $(to_drop).width();
      $clone = $(to_drop).detach();
      $clone.removeClass('drag-wrap');
      $clone.removeClass('getting--dragged');
      $clone.removeClass('draggable');
      $clone.addClass('not-draggable');
      $clone.removeClass(this.bubble_type);
      relative_left = block_offset.left - zone_offset.left;
      relative_top = block_offset.top - zone_offset.top;
      size = $(".droppable-inner-" + type_of_block).children().size();
      x = -125 + 175 + 75 * (size % 3);
      y = -95 + 133 + 75 * Math.floor(size / 3);
      $clone.css({
        '-webkit-transform': "translate(" + 0. + "px, " + 0. + "px)",
        position: 'absolute',
        top: y,
        left: x,
        opacity: 1,
        width: "" + real_diameter,
        height: "" + real_diameter,
        'z-index': 5000
      });
      $clone.prependTo($(".droppable-inner-" + type_of_block));
      $clone.attr('data-x', x);
      $clone.attr('data-y', y);
      items = $(".drag-wrap");
      temp = 10;
      size = $(".droppable-inner-" + type_of_block).children().size();
      return $(".droppable-inner-" + type_of_block).children().each(function(index) {
        return $(this).velocity({
          top: 10,
          left: 10,
          height: 127,
          width: 127,
          opacity: 0.2
        }, {
          duration: 1000
        });
      });
    }
  };

  control_drop_area_.prototype.add_bubble_sections = function() {
    var bubble_size, height_adjustment;
    bubble_size = 130;
    height_adjustment = 90;
    this.who = new bubble_section_(125, 5 + height_adjustment, bubble_size, 'Who');
    this.what = new bubble_section_(195, 240 + height_adjustment, bubble_size, "What");
    this.when = new bubble_section_(5, 110 + height_adjustment, bubble_size, "When");
    this.where = new bubble_section_(240, 110 + height_adjustment, bubble_size, "Where");
    this.why = new bubble_section_(55, 240 + height_adjustment, bubble_size, "Why");
    return $("<div id='expand-navigation' style='\n	background-image:url(http://www.outsource-force.com/blog/wp-content/uploads/2013/11/back-button.png);\n	background-size: 80px 80px;\n	position: absolute;\n	top: 330px;\n	left: -110px;\n	width: 80px;\n	height: 80px;\n	z-index: 3001;\n'>\n</div>").appendTo($("body"));
  };

  control_drop_area_.prototype.add_center_button = function() {
    var $build_button, css;
    $build_button = $("<div id='build_button'>\n	Build\n</div>");
    css = "#build_button {\n	position: absolute;\n	top: 235px;\n	left: 138px;\n	border-radius: 100px;\n	width: 100px;\n	height: 100px;\n	/*background-color: white;*/\n	/*opacity: 0.7;*/\n	line-height: 100px;\n	text-align: center;\n	border: 1px solid black;\n	background: rgba(255, 255, 255,0.8);\n\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $build_button.appendTo($("body"));
    return $build_button.on("tap click", (function(_this) {
      return function() {
        return _this.run();
      };
    })(this));
  };

  control_drop_area_.prototype.run = function() {
    return this.what.run(this.who.run(), this.where.run(), this.why.run);
  };


  /*
  	Ignore the following for now, will need later
   */

  control_drop_area_.prototype.begin_competition = function(competitors) {
    var css;
    $("#matchup-container").remove();
    $("#new-button").remove();
    $("#blackened-background-button").remove();
    $(".drop-zone").css("display", "none");
    $(".drag-zone-background").remove();
    $(".drag-zone").css("display", "none");
    $("#current-step").remove();
    $(".delete-p-tags").remove();
    css = ".instagram-matchup-screen {\n	/*width: 33%;*/\n	display: inline;\n	text-align: center;\n\n}\n\n.profile-pic-matchup {\n	width: 150px;\n	height: auto;\n	border-radius: 200px;\n}\n\n.vs-text {\n	height: 300px;\n	padding: 30px;\n	font-size: 150%;\n	color: white;\n}\n\n.counter-matchup {\n	display: block;\n	color: white;\n}\n\n.not-main-pic {\n	width: 50px;\n	height: auto;\n	border-radius: 200px;\n}\n";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div id='matchup-container'>\n</div>").appendTo($("body"));
    $("<div class='instagram-matchup-screen profile-pic-matchup' style='position:absolute;top:170px;left:10px;'>\n	<img class='profile-pic-matchup' src='" + competitors.first_val[1].images.standard_resolution.url + "'>\n	<img class='not-main-pic' style='position:absolute;top:0px;left:0px;' src='" + competitors.first_val[1].user.profile_picture + "'>\n	<p id=\"instagram-matchup-counter-1\" class='counter-matchup'> TEST HERE 1</p>\n</div>").appendTo($("#matchup-container"));
    $("<div class='instagram-matchup-screen vs-text' style='position:absolute;top:200px;left:140px;'>\n	VS\n</div>").appendTo($("#matchup-container"));
    $("<div class='instagram-matchup-screen profile-pic-matchup' style='position:absolute;top:170px;left:215px;'>\n	<img class='profile-pic-matchup' src='" + competitors.second_val[1].images.standard_resolution.url + "'>\n	<img class='not-main-pic' style='position:absolute;top:0px;right:0px;' src='" + competitors.second_val[1].user.profile_picture + "'>\n	<p id=\"instagram-matchup-counter-2\" class='counter-matchup'> TEST HERE 2</p>\n</div>").appendTo($("#matchup-container"));
    $("body").css('text-align', 'center');
    return $("<p class='delete-p-tags' style='margin:0px;margin-top:450px;font-size:200%;color:white;'> GOAL </p>\n<p id='put-goal-here' class='delete-p-tags' style='margin:0px;font-size:200%;color:white;'> #### </p>").appendTo($("body"));
  };

  control_drop_area_.prototype.show_winner = function(winner, player1) {
    var $container, $info_container, $info_container2;
    $(".delete-p-tags").remove();
    $container = $("#matchup-container");
    $container.html(" ");
    $container.css("text-align", "center");
    if (player1) {
      $("<img id='actual-pic-animation' src='" + winner.images.standard_resolution.url + "' \nstyle='width:150px;height:auto;border-radius:200px;position:absolute;top:170px;left:10px;'>").appendTo($container);
      $info_container = $("<div id='info-matchup-container'></div>");
      $info_container2 = $("<div id='info-matchup-container2'></div>");
      $info_container.appendTo($container);
      $info_container.css({
        "display": 'flex',
        'justify-content': 'center',
        'align-items': 'center'
      });
      $info_container2.appendTo($container);
      $("<img id='profile-pic-animation' src='" + winner.user.profile_picture + "' \nstyle='position:absolute;top:170px;left:10px;\nwidth:50px;height:auto;border-radius:200px;'>").appendTo($info_container);
      $("<p id='results-winnerinfo-1' \nstyle='position:absolute;top:365px;left:120px;\nfont-size:200%;margin:20px;margin-left:10px;color:white;\n'> " + winner.user.username + " </p>").appendTo($info_container);
      $("<p id='results-winnerinfo-2' style='display:block;font-size:200%;color:white;margin-top:440px;padding:0px;'\n> is the WINNER! </p>").appendTo($info_container2);

      /* Animations here */
      $("#results-winnerinfo-1").velocity("fadeIn", {
        'duration': 2500
      });
      $("#results-winnerinfo-2").velocity("fadeIn", {
        'duration': 3000
      });
      $("#actual-pic-animation").velocity({
        top: 80,
        left: 40,
        width: 300,
        height: 300
      });
      return $("#profile-pic-animation").velocity({
        top: 390,
        left: 70
      });
    } else {
      $("<img id='actual-pic-animation' src='" + winner.images.standard_resolution.url + "' \nstyle='width:150px;height:auto;border-radius:200px;position:absolute;top:170px;left:215px;'>").appendTo($container);
      $info_container = $("<div id='info-matchup-container'></div>");
      $info_container2 = $("<div id='info-matchup-container2'></div>");
      $info_container.appendTo($container);
      $info_container.css({
        "display": 'flex',
        'justify-content': 'center',
        'align-items': 'center'
      });
      $info_container2.appendTo($container);
      $("<img id='profile-pic-animation' src='" + winner.user.profile_picture + "' \nstyle='position:absolute;top:170px;left:315px;\nwidth:50px;height:auto;border-radius:200px;'>").appendTo($info_container);
      $("<p id='results-winnerinfo-1' \nstyle='position:absolute;top:365px;left:120px;\nfont-size:200%;margin:20px;margin-left:10px;color:white;\n'> " + winner.user.username + " </p>").appendTo($info_container);
      $("<p id='results-winnerinfo-2' style='display:block;font-size:200%;color:white;margin-top:440px;padding:0px;'\n> is the WINNER! </p>").appendTo($info_container2);

      /* Animations here */
      $("#results-winnerinfo-1").velocity("fadeIn", {
        'duration': 2500
      });
      $("#results-winnerinfo-2").velocity("fadeIn", {
        'duration': 3000
      });
      $("#actual-pic-animation").velocity({
        top: 80,
        left: 40,
        width: 300,
        height: 300
      });
      return $("#profile-pic-animation").velocity({
        top: 390,
        left: 70
      });
    }
  };

  return control_drop_area_;

})();
